services:
  # Web Service
  - type: web
    name: webhook-web
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /
    # Explicitly specify the port
    port: 8080
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: webhook-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: webhook-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: webhook-redis
          type: redis
          property: port
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 8080

  # Worker Service (as web service with health check endpoint)
  - type: web
    name: webhook-worker
    env: docker
    dockerfilePath: ./Dockerfile-worker
    dockerContext: .
    plan: free
    port: 8081
    healthCheckPath: /health
    healthCheckTimeout: 60
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: webhook-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: webhook-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: webhook-redis
          type: redis
          property: port
      - key: PORT
        value: 8081

  # Scheduler Service (as web service with health check endpoint)
  - type: web
    name: webhook-scheduler
    env: docker
    dockerfilePath: ./Dockerfile-scheduler
    dockerContext: .
    plan: free
    port: 8082
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: webhook-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: webhook-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: webhook-redis
          type: redis
          property: port
      - key: PORT
        value: 8082

  # Redis Service
  - type: redis
    name: webhook-redis
    plan: free
    ipAllowList: []

databases:
  - name: webhook-db
    plan: free
    postgresMajorVersion: 13