services:
  # Web Service
  - type: web
    name: webhook-web
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: webhook-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: webhook-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: webhook-redis
          type: redis
          property: port
      - key: SESSION_SECRET
        generateValue: true

  # Worker Service
  - type: worker
    name: webhook-worker
    env: docker
    dockerfilePath: ./Dockerfile-worker
    dockerContext: .
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: webhook-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: webhook-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: webhook-redis
          type: redis
          property: port

  # Scheduler Service
  - type: worker
    name: webhook-scheduler
    env: docker
    dockerfilePath: ./Dockerfile-scheduler
    dockerContext: .
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: webhook-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: webhook-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: webhook-redis
          type: redis
          property: port
        
  # Redis Service
  - type: redis
    name: webhook-redis
    plan: free
    ipAllowList: []

databases:
  - name: webhook-db
    plan: free
    postgresMajorVersion: 13